/****************
Arrays
****************/

// Initialize a new array
var names = ['john', 'jane','mike'];
var years = new Array(1990 , 1969, 1948);

// console.log(typeof names);
// console.log(typeof years);

// Access the array
console.log(names[0]);
console.log(names.length);


// Mutate Array Data

names[2] = 'marry';
names[names.length]='smith';
names[6]= 'mike';

console.log(names);


// Different data types array
var john = ['john','smith', 1990, 'teacher' , true];
console.log(john);

//methods of an array
john.push('blue'); 		
console.log(john);

john.unshift("Mr.");
console.log(john);

john.pop();
console.log(john);

john.shift();
console.log(john);

console.log(john.indexOf(1990));

var arr = names.concat(years);
console.log(arr);

names.pop();
names.pop();
names.pop();
var concat = names.concat(years , john , arr);
console.log(concat);

years.copyWithin(2,0);				// replace the exising value with other one
console.log(years);


var age= [3,10,18,23,33,44];

function checkAdult(age){
	return age > 18;
}

console.log("entries output: ");
var x=names.entries();
for (f of x){
	console.log(f);
}

console.log(age.every(checkAdult));		// check whether all elements pass the test if passes then return true else return false

console.log(age.some(checkAdult));		// check whether any of the element pass the test

console.log(age.filter(checkAdult));	// return all elements which passes the test

console.log(age.find(checkAdult));		// return first element which passes the test

// console.log(age.fill(18));				// fill an entire array with specified value

console.log(age.findIndex(checkAdult));	// returns the index of first element which passes the test

console.log(age.includes(18));			//check whether specified element is there in the array

var arr1= ['Saloni','Sindhi','is','a','new','intern'];
console.log(arr1.join(" "));			// convert array into string

var no = [4,9,16,25,36];
var nos=no.map(Math.sqrt)				// creates an array of results which generated by each element in an array from the function.
console.log(nos);

var numbers=[200,125,25];
function myFunc(total,num){
	return total-num;
}
console.log(numbers.reduce(myFunc));	// subtract the elements of an array starting from left to right

console.log(no.reduceRight(myFunc));	// subtract a number of an array from right to left	

console.log(no.reverse());				// reverse an order of an array

var slice=no.slice(1,3);
console.log(slice);						// creates a new sub array of an existing array

console.log(no.sort());					// sort an array elements


